apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scalardb-graphql.fullname" . }}-config-file
data:
  # Create a database.properties file which is config file of Scalar DB server.
  database.properties: |-
    scalar.db.contact_points={{.Values.scalarDbGraphQlConfiguration.contactPoints}}
    scalar.db.contact_port={{.Values.scalarDbGraphQlConfiguration.contactPort}}
    scalar.db.username={{.Values.scalarDbGraphQlConfiguration.username}}
    scalar.db.password={{.Values.scalarDbGraphQlConfiguration.password}}
    scalar.db.storage={{.Values.scalarDbGraphQlConfiguration.storage}}
    scalar.db.transaction_manager={{.Values.scalarDbGraphQlConfiguration.transactionManager}}
    scalar.db.graphql.port=8080
    scalar.db.graphql.path={{.Values.scalarDbGraphQlConfiguration.path}}
    scalar.db.graphql.namespaces={{.Values.scalarDbGraphQlConfiguration.namespaces}}
    scalar.db.graphql.graphiql={{.Values.scalarDbGraphQlConfiguration.graphiql}}
