apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scalardb-graphql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scalardb-graphql.labels" . | nindent 4 }}
spec:
  minReadySeconds: 0
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "scalardb-graphql.selectorLabels" . | nindent 6 }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "scalardb-graphql.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Always
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 60
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: SCALAR_DB_CONTACT_POINTS
              value: "{{ .Values.scalarDbGraphQlConfiguration.contactPoints }}"
            - name: SCALAR_DB_CONTACT_PORT
              value: "{{ .Values.scalarDbGraphQlConfiguration.contactPort }}"
            - name: SCALAR_DB_USERNAME
              valueFrom:
                secretKeyRef:
                {{- if .Values.existingSecret }}
                  name: {{ .Values.existingSecret }}
                {{- else }}
                  name: {{ include "scalardb-graphql.fullname" . }}-secret
                {{- end }}
                  key: db-username
            - name: SCALAR_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                {{- if .Values.existingSecret }}
                  name: {{ .Values.existingSecret }}
                {{- else }}
                  name: {{ include "scalardb-graphql.fullname" . }}-secret
                {{- end }}
                  key: db-password
            - name: SCALAR_DB_STORAGE
              value: "{{ .Values.scalarDbGraphQlConfiguration.storage }}"
            - name: SCALAR_DB_TRANSACTION_MANAGER
              value: "{{ .Values.scalarDbGraphQlConfiguration.transactionManager }}"
            - name: SCALAR_DB_CONSENSUSCOMMIT_ISOLATION_LEVEL
              value: "{{ .Values.scalarDbGraphQlConfiguration.consensuscommitIsolationLevel }}"
            - name: SCALAR_DB_CONSENSUSCOMMIT_SERIALIZABLE_STRATEGY
              value: "{{ .Values.scalarDbGraphQlConfiguration.consensuscommitSerializableStrategy }}"
            - name: SCALAR_DB_GRAPHQL_PORT
              value: ""
            - name: SCALAR_DB_GRAPHQL_PATH
              value: "{{ .Values.scalarDbGraphQlConfiguration.path }}"
            - name: SCALAR_DB_GRAPHQL_NAMESPACES
              value: "{{ .Values.scalarDbGraphQlConfiguration.namespaces }}"
            - name: SCALAR_DB_GRAPHQL_GRAPHIQL
              value: "{{ .Values.scalarDbGraphQlConfiguration.graphiql }}"
            - name: SCALAR_DB_GRAPHQL_LOG_LEVEL
              value: "{{ .Values.scalarDbGraphQlConfiguration.logLevel }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: "{{ .Values.scalarDbGraphQlConfiguration.path }}?query=%7B__typename%7D"
              port: 8080
          readinessProbe:
            httpGet:
              path: "{{ .Values.scalarDbGraphQlConfiguration.path }}?query=%7B__typename%7D"
              port: 8080
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
