{{- if ( .Values.prometheusRule.enabled ) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: prometheus-operator
    release: prometheus
  name: {{ include "scalardb-graphql.fullname" . }}-prometheus-alerts-rules
{{- if .Values.prometheusRule.namespace }}
  namespace: {{ .Values.prometheusRule.namespace }}
{{- end }}
spec:
  groups:
  - name: ScalarDbGraphQlAlerts
    rules:
    - alert: ScalarDbGraphQlClusterDown
      expr: kube_deployment_spec_replicas{deployment="{{ include "scalardb-graphql.fullname" . }}"} - kube_deployment_status_replicas_unavailable{deployment="{{ include "scalardb-graphql.fullname" . }}"} == 0
      for: 1m
      labels:
        severity: critical
        app: ScalarDbGraphQl
      annotations:
        summary: 'ScalarDB GraphQL cluster is down'
        description: 'ScalarDB GraphQL cluster is down, no resquest can be process'

    - alert: ScalarDbGraphQlClusterDegraded
      expr: kube_deployment_status_replicas_unavailable{namespace="{{ .Release.Namespace }}", deployment="{{ include "scalardb-graphql.fullname" . }}"} >= 1
      for: 1m
      labels:
        severity: warning
        app: ScalarDbGraphQl
      annotations:
        summary: 'ScalarDB GraphQL cluster is running in a degraded mode'
        description: 'ScalarDB GraphQL cluster is running in a degraded mode, some of the ScalarDB GraphQL pods are not healthy'

    - alert: ScalarDbGraphQlPodsPending
      expr: kube_pod_status_phase{namespace="{{ .Release.Namespace }}", pod=~"^{{ include "scalardb-graphql.fullname" . }}-.*", phase="Pending"} > 0
      for: 1m
      labels:
        severity: warning
        app: ScalarDbGraphQl
      annotations:
        description: 'Pod {{`{{$labels.pod}}`}} in namespace {{`{{$labels.namespace}}`}} has been in pending status for more than 1 minute.'
        summary: 'Pod {{`{{$labels.pod}}`}} in namespace {{`{{$labels.namespace}}`}} in pending status.'

    - alert: ScalarDbGraphQlPodsError
      expr: kube_pod_container_status_waiting_reason{namespace="{{ .Release.Namespace }}",reason!="ContainerCreating",pod=~"^{{ include "scalardb-graphql.fullname" . }}-.*"} > 0
      for: 1m
      labels:
        severity: warning
        app: ScalarDbGraphQl
      annotations:
        description: 'Pod {{`{{$labels.pod}}`}} in namespace {{`{{$labels.namespace}}`}} has an error for more than 1 minute.'
        summary: 'Pod {{`{{$labels.pod}}`}} in namespace {{`{{$labels.namespace}}`}} has an error status.'
{{- end }}
