{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scalardb-graphql.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scalardb-graphql.labels" . | nindent 4 }}
type: Opaque
data:
  db-username: {{ .Values.scalarDbGraphQlConfiguration.username | b64enc | quote }}
  db-password: {{ .Values.scalarDbGraphQlConfiguration.password | b64enc | quote }}
{{- end -}}
