apiVersion: v1
kind: Service
metadata:
  name: {{ include "scalardb-graphql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scalardb-graphql.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "scalardb-graphql.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scalardb-graphql.fullname" . }}-metrics
  labels:
    {{- include "scalardb-graphql.labels" . | nindent 4 }}
spec:
  ports:
  - name: scalardb-graphql-prometheus
    port: 9080
    targetPort: 9080
    protocol: TCP
  selector:
    {{- include "scalardb-graphql.selectorLabels" . | nindent 4 }}
  type: ClusterIP
