apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "scalar-admin-for-kubernetes.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
