apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "scalar-manager.fullname" . }}-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ include "scalar-manager.serviceAccountName" . }}
  apiGroup: ""
roleRef:
  kind: Role
  name: {{ include "scalar-manager.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
