apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "scalar-manager.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
