{{- if not .Values.serviceAccount.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "scalar-manager.serviceAccountName" . }}
  labels:
    {{- include "scalar-manager.labels" . | nindent 4 }}
{{- end }}
