apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-loading-config
data:
  database.properties: |-
    scalar.db.contact_points=jdbc:postgresql://postgresql.default.svc.cluster.local:5432/postgres
    scalar.db.contact_port=9042
    scalar.db.username=postgres
    scalar.db.password=postgres
    scalar.db.storage=jdbc
  schema.json: |-
    {
      "ct.t1": {
        "transaction": true,
        "partition-key": [
          "c1"
        ],
        "clustering-key": [
          "c2"
        ],
        "columns": {
          "c1": "INT",
          "c2": "INT",
          "c3": "INT"
        }
      }
    }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: schema-loading
spec:
  template:
    metadata:
      labels:
        app: schema-loading
    spec:
      containers:
      - name: schema-loading
        image: ghcr.io/scalar-labs/scalardb-schema-loader:4.0.0-SNAPSHOT
        imagePullPolicy: IfNotPresent
        args:
        - "-c"
        - "/config/database.properties"
        - "-f"
        - "/config/schema.json"
        - "--coordinator"
        volumeMounts:
        - name: schema-loading-config-volume
          mountPath: /config
      volumes:
      - name: schema-loading-config-volume
        configMap:
          name: schema-loading-config
      restartPolicy: Never
  backoffLimit: 0
