apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scalardb.fullname" . }}-config-file
data:
  # Create a database.properties file which is config file of Scalar DB server.
  database.properties: |-
    scalar.db.contact_points={{.Values.scalardb.storageConfiguration.contactPoints}}
    scalar.db.contact_port={{.Values.scalardb.storageConfiguration.contactPort}}
    scalar.db.username={{.Values.scalardb.storageConfiguration.username}}
    scalar.db.password={{.Values.scalardb.storageConfiguration.password}}
    scalar.db.storage={{.Values.scalardb.storageConfiguration.storage}}
