apiVersion: v1
kind: Service
metadata:
  name: {{ include "scalardb.fullname" . }}
  labels:
    {{- include "scalardb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.scalardb.service.type }}
  ports:
    {{- range $key, $value := .Values.scalardb.service.ports }}
    - name: {{ $key }}
{{ toYaml $value | indent 6 }}
  {{- end }}
  selector:
    {{- include "scalardb.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scalardb.fullname" . }}-metrics
  labels:
    {{- include "scalardb.labels" . | nindent 4 }}
spec:
  ports:
  - name: scalardb-prometheus
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    {{- include "scalardb.selectorLabels" . | nindent 4 }}
  type: ClusterIP
