apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scalardb-analytics-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
spec:
  ingressClassName: nginx
  rules:
  - host: local.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: scalardb-analytics-svc
            port:
              number: 50051
  tls:
  - hosts:
      - local.example.com
    secretName: ingress-tls-secret
