{
 "title": "Scalar DB / Overview",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": {
     "query": "label_values(scalardb_stats_total_success, pod) "
    }
   }
  ]
 },
 "panels": [
  { "title": "Total Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success Requests per one second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scalardb_stats_total_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failure Requests per one second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scalardb_stats_total_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Distributed Storage Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true
  },
  {
   "title": "Get per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_stats_distributed_storage_get_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Get execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "scalardb_stats_distributed_storage_get{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_get{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_get{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_get{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_get{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_get{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Open scanner per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_stats_distributed_storage_scan_open_scanner_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Open scanner execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "scalardb_stats_distributed_storage_scan_open_scanner{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_scan_open_scanner{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_scan_open_scanner{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_scan_open_scanner{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_scan_open_scanner{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_scan_open_scanner{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Scan next per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_stats_distributed_storage_scan_next_count{pod=~\"$pod\"} [1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Scan next execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "scalardb_stats_distributed_storage_scan_next{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_scan_next{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_scan_next{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_scan_next{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_scan_next{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_scan_next{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Mutate per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_stats_distributed_storage_mutate_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Mutate execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "scalardb_stats_distributed_storage_mutate{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_mutate{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_mutate{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_mutate{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_mutate{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_mutate{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Distributed Storage Admin Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true
  },
  {
   "title": "Create table per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_stats_distributed_storage_admin_create_table_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Create table execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "scalardb_stats_distributed_storage_admin_create_table{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_admin_create_table{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_admin_create_table{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_admin_create_table{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_admin_create_table{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_admin_create_table{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Drop table per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_stats_distributed_storage_admin_drop_table_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Drop table execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "scalardb_stats_distributed_storage_admin_drop_table{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_admin_drop_table{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_admin_drop_table{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_admin_drop_table{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_admin_drop_table{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_admin_drop_table{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Truncate table per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_stats_distributed_storage_admin_truncate_table_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Truncate table execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "scalardb_stats_distributed_storage_admin_truncate_table{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_admin_truncate_table{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_admin_truncate_table{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_admin_truncate_table{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_admin_truncate_table{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_admin_truncate_table{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Get table metadata per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_stats_distributed_storage_admin_get_table_metadata_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Get table metadata execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "scalardb_stats_distributed_storage_admin_get_table_metadata{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_admin_get_table_metadata{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_admin_get_table_metadata{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_admin_get_table_metadata{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_admin_get_table_metadata{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_storage_admin_get_table_metadata{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Distributed Transaction Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true
  },
  {
   "title": "Transaction start per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_stats_distributed_transaction_transaction_start_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transaction start execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_start{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_start{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_start{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_start{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_start{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_start{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction get per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_stats_distributed_transaction_transaction_get_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transaction get execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "targets": [
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_get{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_get{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_get{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_get{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_get{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_get{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction scan per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_stats_distributed_transaction_transaction_scan_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transaction scan execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "targets": [
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_scan{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_scan{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_scan{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_scan{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_scan{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_scan{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction mutate per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_stats_distributed_transaction_transaction_mutate_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transaction mutate execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "targets": [
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_mutate{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_mutate{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_mutate{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_mutate{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_mutate{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_mutate{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction commit per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_stats_distributed_transaction_transaction_commit_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transaction commit execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "targets": [
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_commit{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_commit{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_commit{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_commit{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_commit{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_commit{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction abort per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_stats_distributed_transaction_transaction_abort_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transaction abort execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "targets": [
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_abort{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_abort{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_abort{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_abort{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_abort{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_abort{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Get state per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_stats_distributed_transaction_get_state_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Get state execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "targets": [
    {
     "expr": "scalardb_stats_distributed_transaction_get_state{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_get_state{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_get_state{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_get_state{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_get_state{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_get_state{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Abort per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_stats_distributed_transaction_transaction_abort_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Abort execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
   "targets": [
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_abort{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_abort{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_abort{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_abort{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_abort{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_distributed_transaction_transaction_abort{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Two Phase Commit Transaction Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 }
  },
  {
   "title": "Get state per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_get_state_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_get_state_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_get_state_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Get state execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 140 },
   "targets": [
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_get_state{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_get_state{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_get_state{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_get_state{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_get_state{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_get_state{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Abort per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_abort_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_abort_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_abort_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Abort execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
   "targets": [
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_abort{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_abort{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_abort{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_abort{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_abort{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_abort{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction start per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 156 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_transaction_start_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_transaction_start_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_transaction_start_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Transaction start execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 156 },
   "targets": [
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_start{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_start{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_start{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_start{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_start{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_start{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction join per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_transaction_join_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_transaction_join_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_transaction_join_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Transaction join execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
   "targets": [
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_join{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_join{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_join{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_join{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_join{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_join{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction get per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 172 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_transaction_get_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_transaction_get_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_transaction_get_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Transaction get execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 172 },
   "targets": [
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_get{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_get{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_get{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_get{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_get{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_get{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction scan per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 180 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_transaction_scan_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_transaction_scan_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_transaction_scan_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Transaction scan execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 180 },
   "targets": [
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_scan{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_scan{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_scan{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_scan{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_scan{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_scan{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction mutate per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 188 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_transaction_mutate_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_transaction_mutate_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_transaction_mutate_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Transaction mutate execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 188 },
   "targets": [
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_mutate{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_mutate{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_mutate{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_mutate{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_mutate{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_mutate{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction prepare per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 196 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_transaction_prepare_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_transaction_prepare_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_transaction_prepare_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Transaction prepare execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 196 },
   "targets": [
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_prepare{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_prepare{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_prepare{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_prepare{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_prepare{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_prepare{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction validate per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 204 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_transaction_validate_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_transaction_validate_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_transaction_validate_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Transaction validate execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 204 },
   "targets": [
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_validate{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_validate{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_validate{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_validate{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_validate{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_validate{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction commit per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 212 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_transaction_commit_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_transaction_commit_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_transaction_commit_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Transaction commit execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 212 },
   "targets": [
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_commit{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_commit{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_commit{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_commit{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_commit{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_commit{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction rollback per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 220 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_transaction_rollback_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_transaction_rollback_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_stats_two_phase_commit_transaction_transaction_rollback_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Transaction rollback execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 220 },
   "targets": [
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_rollback{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_rollback{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_rollback{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_rollback{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_rollback{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_stats_two_phase_commit_transaction_transaction_rollback{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  }
 ]
}