apiVersion: v1
kind: Pod
metadata:
  name: scalardb-sql-cli
spec:
  containers:
    - name: scalardb-sql-cli
      image: ghcr.io/scalar-labs/scalardb-sql-cli:3.6.0
      command: ['sleep']
      args: ['inf']
      volumeMounts:
        - name: database-properties
          mountPath: "/conf"
          readOnly: true
  imagePullSecrets:
    - name: reg-docker-secrets
  volumes:
    - name: database-properties
      configMap:
        name: database-properties
  restartPolicy: Never
