{
 "title": "ScalarDB GraphQL / Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": {
     "query": "label_values(scalardb_graphql_stats_graphql_success, pod) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Success HTTP Requests per one second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(scalardb_graphql_stats_http_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failure HTTP Requests per one second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(scalardb_graphql_stats_http_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Success GraphQL Queries per one second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(scalardb_graphql_stats_graphql_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failure GraphQL Queries per one second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(scalardb_graphql_stats_graphql_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GraphQL execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "scalardb_graphql_stats_responses{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_graphql_stats_responses{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_graphql_stats_responses{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_graphql_stats_responses{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_graphql_stats_responses{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_graphql_stats_responses{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  }
 ]
}