{
 "title": "ScalarDL Auditor / Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "pod",
    "query": {
     "query": "label_values(scalardl_stats_auditor_total_success, pod) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Success Requests Per One Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(scalardl_stats_auditor_total_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failure Requests Per One Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(scalardl_stats_auditor_total_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Certificate Registration Request Per One Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(irate(scalardl_stats_auditor_certificate_registration_request_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardl_stats_auditor_certificate_registration_request_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardl_stats_auditor_certificate_registration_request_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Certificate Registration Request Execution Time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "scalardl_stats_auditor_certificate_registration_request{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_auditor_certificate_registration_request{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_auditor_certificate_registration_request{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_auditor_certificate_registration_request{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_auditor_certificate_registration_request{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_auditor_certificate_registration_request{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Contract Execution Request Per One Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(irate(scalardl_stats_auditor_contract_execution_request_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardl_stats_auditor_contract_execution_request_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardl_stats_auditor_contract_execution_request_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Contract Execution Request Execution Time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "scalardl_stats_auditor_contract_execution_request{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_auditor_contract_execution_request{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_auditor_contract_execution_request{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_auditor_contract_execution_request{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_auditor_contract_execution_request{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_auditor_contract_execution_request{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Execution Validation Request Per One Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(irate(scalardl_stats_auditor_execution_validation_request_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardl_stats_auditor_execution_validation_request_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardl_stats_auditor_execution_validation_request_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Execution Validation Request Execution Time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "scalardl_stats_auditor_execution_validation_request{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_auditor_execution_validation_request{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_auditor_execution_validation_request{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_auditor_execution_validation_request{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_auditor_execution_validation_request{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_auditor_execution_validation_request{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Ledger Validation Request Per One Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(irate(scalardl_stats_auditor_ledger_validation_request_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardl_stats_auditor_ledger_validation_request_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardl_stats_auditor_ledger_validation_request_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Ledger Validation Request Execution Time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "scalardl_stats_auditor_ledger_validation_request{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_auditor_ledger_validation_request{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_auditor_ledger_validation_request{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_auditor_ledger_validation_request{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_auditor_ledger_validation_request{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_auditor_ledger_validation_request{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  }
 ]
}