{
 "title": "Scalar / Envoy Proxy / Overview",
 "description": "Envoy proxy monitoring Dashboard with cluster and host level templates. ",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(envoy_cluster_upstream_cx_total, envoy_cluster_name)"
    }
   },
   {
    "name": "pods",
    "label": "Pods",
    "query": {
     "query": "label_values(envoy_cluster_version{envoy_cluster_name=\"${cluster}\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Live servers",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(envoy_server_live)" }
   ]
  },
  {
   "title": "Avg uptime per node",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(envoy_server_uptime)" }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "SUM(envoy_server_memory_allocated)"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "SUM(envoy_server_memory_heap_size)"
    }
   ]
  },
  {
   "title": "Unhealthy Clusters",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_membership_total{envoy_cluster_name=~\"$cluster\"}) - sum(envoy_cluster_membership_healthy{envoy_cluster_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Cluster State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_total{envoy_cluster_name=~\"$cluster\"}) - sum(envoy_cluster_membership_healthy{envoy_cluster_name=~\"$cluster\"})) == bool 0"
    }
   ]
  },
  {
   "title": "Total active connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_active{envoy_cluster_name=~\"$cluster\",pod=~\"$pods\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"$cluster\",pod=~\"$pods\"}[1m])",
     "legendFormat": "{{pod}} - total"
    },
    {
     "expr": "irate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"2\",envoy_cluster_name=~\"$cluster\",pod=~\"$pods\"}[1m])",
     "legendFormat": "{{pod}} - 2xx"
    },
    {
     "expr": "irate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"3\",envoy_cluster_name=~\"$cluster\",pod=~\"$pods\"}[1m])",
     "legendFormat": "{{pod}} - 3xx"
    },
    {
     "expr": "irate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"4\",envoy_cluster_name=~\"$cluster\",pod=~\"$pods\"}[1m])",
     "legendFormat": "{{pod}} - 4xx"
    },
    {
     "expr": "irate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"5\",envoy_cluster_name=~\"$cluster\",pod=~\"$pods\"}[1m])",
     "legendFormat": "{{pod}} - 5xx"
    }
   ]
  },
  {
   "title": "Downstream Total active connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_http_downstream_cx_active{envoy_http_conn_manager_prefix=~\"ingress_http\",pod=~\"$pods\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Downstream Total active requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_http_downstream_rq_total{envoy_http_conn_manager_prefix=~\"ingress_http\",pod=~\"$pods\"}[1m])",
     "legendFormat": "{{pod}} - total"
    },
    {
     "expr": "irate(envoy_http_downstream_rq_xx{envoy_response_code_class=\"2\",envoy_http_conn_manager_prefix=~\"ingress_http\",pod=~\"$pods\"}[1m])",
     "legendFormat": "{{pod}} - 2xx"
    },
    {
     "expr": "irate(envoy_http_downstream_rq_xx{envoy_response_code_class=\"3\",envoy_http_conn_manager_prefix=~\"ingress_http\",pod=~\"$pods\"}[1m])",
     "legendFormat": "{{pod}} - 3xx"
    },
    {
     "expr": "irate(envoy_http_downstream_rq_xx{envoy_response_code_class=\"4\",envoy_http_conn_manager_prefix=~\"ingress_http\",pod=~\"$pods\"}[1m])",
     "legendFormat": "{{pod}} - 4xx"
    },
    {
     "expr": "irate(envoy_http_downstream_rq_xx{envoy_response_code_class=\"5\",envoy_http_conn_manager_prefix=~\"ingress_http\",host=~\"$pods\"}[1m])",
     "legendFormat": "{{pod}} - 5xx"
    }
   ]
  },
  {
   "title": "Upstream Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_cluster_upstream_cx_rx_bytes_total{envoy_cluster_name=~\"$cluster\",pod=~\"$pods\"}[1m])",
     "legendFormat": "{{pod}} - in"
    },
    {
     "expr": "irate(envoy_cluster_upstream_cx_tx_bytes_total{envoy_cluster_name=~\"$cluster\",pod=~\"$pods\"}[1m])",
     "legendFormat": "{{pod}} - out"
    }
   ]
  },
  {
   "title": "Downstream Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_http_downstream_cx_rx_bytes_total{envoy_http_conn_manager_prefix=~\"ingress_http\",pod=~\"$pods\"}[1m])",
     "legendFormat": "{{pod}} - in"
    },
    {
     "expr": "irate(envoy_http_downstream_cx_tx_bytes_total{envoy_http_conn_manager_prefix=~\"ingress_http\",pod=~\"$pods\"}[1m])",
     "legendFormat": "{{pod}} - out"
    }
   ]
  },
  {
   "title": "Downstream members",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_membership_healthy{envoy_cluster_name=\"$cluster\",pod=~\"$pods\"})/count(envoy_cluster_membership_healthy{envoy_cluster_name=\"$cluster\",pod=~\"$pods\"})",
     "legendFormat": "healthy"
    },
    {
     "expr": "sum(envoy_cluster_membership_total{envoy_cluster_name=\"$cluster\",pod=~\"$pods\"})/count(envoy_cluster_membership_total{envoy_cluster_name=\"$cluster\",pod=~\"$pods\"})",
     "legendFormat": "total"
    }
   ]
  }
 ]
}