apiVersion: batch/v1
kind: Job
metadata:
  name: ist-loader
  labels:
    {{- include "ist-loader.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "ist-loader.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.istLoader.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: scalar-ist-loader
          image: "{{ .Values.istLoader.image.repository }}:{{ .Values.istLoader.image.version }}"
          imagePullPolicy: "{{ .Values.istLoader.image.pullPolicy }}" 
          env:
            - name: CLIENT_PROPERTIES_PATH
              value: properties/client.properties 
            - name: LEDGER_HOST
              value: dl-scalardl-ledger-headless 
          volumeMounts:
            - name: client-properties
              mountPath: /properties
              readOnly: true
            - name: ist-credentials
              mountPath: /etc/secret-volume
  # The secret data is exposed to Containers in the Pod through a Volume.
      volumes:
        - name: ist-credentials
          secret:
            secretName: ist-credentials
        - name: client-properties
          configMap:
            name: client-properties
      restartPolicy: OnFailure
  backoffLimit: 4
