apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scalardl.fullname" . }}-ledger-properties
  namespace: {{ .Release.Namespace }}
data:
  # Create a ledger.properties file which is config file of ScalarDL Ledger.
  ledger.properties.tmpl:
    {{- toYaml .Values.ledger.ledgerProperties | nindent 4 }}
---
{{- if .Values.ledger.grafanaDashboard.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scalardl.fullname" . }}-ledger-grafana-dashboard
  labels:
    grafana_dashboard: "1"
    {{- include "scalardl-ledger.labels" . | nindent 4 }}
{{- if .Values.ledger.grafanaDashboard.namespace }}
  namespace: {{ .Values.ledger.grafanaDashboard.namespace }}
{{- end }}
data:
{{- range $path, $_ :=  .Files.Glob  "files/grafana/scalardl_*.json" }}
  {{ $path | base }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
{{- end }}
