apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scalardl.fullname" . }}-ledger
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scalardl-ledger.labels" . | nindent 4 }}
spec:
  minReadySeconds: 0
  replicas: {{ .Values.ledger.replicaCount }}
  selector:
    matchLabels:
      {{- include "scalardl-ledger.selectorLabels" . | nindent 6 }}
  {{- with .Values.ledger.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/ledger/configmap.yaml") . | sha256sum }}
        {{- if .Values.ledger.podAnnotations }}
        {{- toYaml .Values.ledger.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        {{- $podLabels := .Values.ledger.podLabels | default dict }}
        {{- $selectorLabels := include "scalardl-ledger.selectorLabels" . | fromYaml }}
        {{- toYaml (merge $selectorLabels $podLabels) | nindent 8 }}
        {{- if eq .Values.global.platform "azure" }}
        azure-extensions-usage-release-identifier: {{ .Release.Name }}
        {{- end }}
    spec:
      restartPolicy: Always
      {{- if .Values.ledger.serviceAccount.serviceAccountName }}
      serviceAccountName: {{ .Values.ledger.serviceAccount.serviceAccountName }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.ledger.serviceAccount.automountServiceAccountToken }}
      terminationGracePeriodSeconds: 60
    {{- with .Values.ledger.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.ledger.podSecurityContext | nindent 8 }}
      volumes:
      {{- if .Values.ledger.scalarLedgerConfiguration.ledgerProofEnabled }}
        - name: "{{ .Values.ledger.scalarLedgerConfiguration.secretName }}"
          secret:
            secretName: "{{ .Values.ledger.scalarLedgerConfiguration.secretName }}"
      {{- end }}
        - name: scalardl-ledger-properties-volume
          configMap:
            name: {{ include "scalardl.fullname" . }}-ledger-properties
      {{- if and .Values.ledger.tls.enabled .Values.ledger.tls.certManager.enabled }}
        - name: scalardl-ledger-tls-volume
          secret:
            secretName: {{ include "scalardl.fullname" . }}-tls-cert
      {{- end }}
      {{- if and (.Values.ledger.tls.enabled) (not .Values.ledger.tls.certManager.enabled) }}
        - name: scalardl-ledger-tls-volume
          projected:
            sources:
              - secret:
                  name: {{ .Values.ledger.tls.caRootCertSecret }}
              - secret:
                  name: {{ .Values.ledger.tls.certChainSecret }}
              - secret:
                  name: {{ .Values.ledger.tls.privateKeySecret }}
      {{- end }}
      {{- with .Values.ledger.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-ledger
          securityContext:
            {{- toYaml .Values.ledger.securityContext | nindent 12 }}
          {{- if eq .Values.global.platform "azure" }}
          image: "{{ .Values.global.azure.images.scalardlLedger.registry }}/{{ .Values.global.azure.images.scalardlLedger.image }}:{{ .Values.global.azure.images.scalardlLedger.tag }}"
          {{- else }}
          image: "{{ .Values.ledger.image.repository }}:{{ .Values.ledger.image.version }}"
          {{- end }}
          imagePullPolicy: {{ .Values.ledger.image.pullPolicy }}
          volumeMounts:
          {{- if .Values.ledger.scalarLedgerConfiguration.ledgerProofEnabled }}
            - name: "{{ .Values.ledger.scalarLedgerConfiguration.secretName }}"
              mountPath: "/keys"
              readOnly: true
          {{- end }}
            - name: scalardl-ledger-properties-volume
              mountPath: /scalar/ledger/ledger.properties.tmpl
              subPath: ledger.properties.tmpl
          {{- if .Values.ledger.tls.enabled }}
            - name: scalardl-ledger-tls-volume
              mountPath: /tls/scalardl-ledger/certs
          {{- end }}
          {{- with .Values.ledger.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
          - containerPort: 50051
          - containerPort: 50052
          - containerPort: 50053
          - containerPort: 8080
          env:
          - name: HELM_SCALAR_DB_CONTACT_POINTS
            value: "{{ .Values.ledger.scalarLedgerConfiguration.dbContactPoints }}"
          - name: HELM_SCALAR_DB_CONTACT_PORT
            value: "{{ .Values.ledger.scalarLedgerConfiguration.dbContactPort }}"
          - name: HELM_SCALAR_DB_USERNAME
            valueFrom:
              secretKeyRef:
              {{- if .Values.ledger.existingSecret }}
                name: {{ .Values.ledger.existingSecret }}
              {{- else }}
                name: {{ include "scalardl.fullname" . }}-ledger
              {{- end }}
                key: db-username
          - name: HELM_SCALAR_DB_PASSWORD
            valueFrom:
              secretKeyRef:
              {{- if .Values.ledger.existingSecret }}
                name: {{ .Values.ledger.existingSecret }}
              {{- else }}
                name: {{ include "scalardl.fullname" . }}-ledger
              {{- end }}
                key: db-password
          - name: HELM_SCALAR_DB_STORAGE
            value: "{{ .Values.ledger.scalarLedgerConfiguration.dbStorage }}"
          - name: SCALAR_DL_LEDGER_LOG_LEVEL
            value: "{{ .Values.ledger.scalarLedgerConfiguration.ledgerLogLevel }}"
          - name: HELM_SCALAR_DL_LEDGER_PROOF_ENABLED
            value: "{{ .Values.ledger.scalarLedgerConfiguration.ledgerProofEnabled }}"
          - name: HELM_SCALAR_DL_LEDGER_PROOF_PRIVATE_KEY_PATH
            value: "/keys/{{ .Values.ledger.scalarLedgerConfiguration.ledgerPrivateKeySecretKey }}"
          {{- if .Values.ledger.scalarLedgerConfiguration.ledgerAuditorEnabled }}
          - name: HELM_SCALAR_DL_LEDGER_AUDITOR_ENABLED
            value: "{{ .Values.ledger.scalarLedgerConfiguration.ledgerAuditorEnabled }}"
          {{- end }}
          {{- if .Values.ledger.secretName }}
          envFrom:
          - secretRef:
              name: "{{ .Values.ledger.secretName }}"
          {{- end }}
          startupProbe:
            exec:
              command:
              - /usr/local/bin/grpc_health_probe
              - -addr=localhost:50051
              {{- if .Values.ledger.tls.enabled }}
              - -tls
              - -tls-ca-cert=/tls/scalardl-ledger/certs/ca.crt
              {{- if .Values.ledger.tls.overrideAuthority }}
              - -tls-server-name={{ .Values.ledger.tls.overrideAuthority }}
              {{- end }}
              {{- end }}
            failureThreshold: 60
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
              - /usr/local/bin/grpc_health_probe
              - -addr=localhost:50051
              {{- if .Values.ledger.tls.enabled }}
              - -tls
              - -tls-ca-cert=/tls/scalardl-ledger/certs/ca.crt
              {{- if .Values.ledger.tls.overrideAuthority }}
              - -tls-server-name={{ .Values.ledger.tls.overrideAuthority }}
              {{- end }}
              {{- end }}
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            {{- toYaml .Values.ledger.resources | nindent 12 }}
      {{- with .Values.ledger.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.ledger.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.ledger.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
