{{- if not .Values.scalarAdminForKubernetes.serviceAccount.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scalar-admin-for-kubernetes.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scalar-admin-for-kubernetes.labels" . | nindent 4 }}
{{- end }}
