{
 "title": "ScalarDL / Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "pod",
    "query": {
     "query": "label_values(scalardl_stats_ledger_total_success, pod) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Success Requests Per One Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(scalardl_stats_ledger_total_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failure Requests Per One Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(scalardl_stats_ledger_total_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Contract Registration Request Per One Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(irate(scalardl_stats_ledger_contract_registration_request_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardl_stats_ledger_contract_registration_request_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardl_stats_ledger_contract_registration_request_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Contract Registration Request Execution Time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "scalardl_stats_ledger_contract_registration_request{quantile=\"0.5\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_ledger_contract_registration_request{quantile=\"0.75\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_ledger_contract_registration_request{quantile=\"0.95\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_ledger_contract_registration_request{quantile=\"0.98\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_ledger_contract_registration_request{quantile=\"0.99\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_ledger_contract_registration_request{quantile=\"0.999\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Contract Execution Request Per One Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(irate(scalardl_stats_ledger_contract_execution_request_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardl_stats_ledger_contract_execution_request_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardl_stats_ledger_contract_execution_request_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Contract Execution Request Execution Time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "scalardl_stats_ledger_contract_execution_request{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_ledger_contract_execution_request{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_ledger_contract_execution_request{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_ledger_contract_execution_request{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_ledger_contract_execution_request{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_ledger_contract_execution_request{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Certificate Registration Request Per One Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(scalardl_stats_ledger_certificate_registration_request_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardl_stats_ledger_certificate_registration_request_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardl_stats_ledger_certificate_registration_request_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Certificate Registration Request Execution Time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "scalardl_stats_ledger_certificate_registration_request{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_ledger_certificate_registration_request{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_ledger_certificate_registration_request{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_ledger_certificate_registration_request{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_ledger_certificate_registration_request{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_ledger_certificate_registration_request{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Execution Abort Request Per One Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(irate(scalardl_stats_ledger_execution_abort_request_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardl_stats_ledger_execution_abort_request_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardl_stats_ledger_execution_abort_request_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Execution Abort Request Execution Time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "scalardl_stats_ledger_execution_abort_request{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_ledger_execution_abort_request{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_ledger_execution_abort_request{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_ledger_execution_abort_request{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_ledger_execution_abort_request{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_ledger_execution_abort_request{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Asset Proof Retrieval Request Per One Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(irate(scalardl_stats_ledger_asset_proof_retrieval_request_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardl_stats_ledger_asset_proof_retrieval_request_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardl_stats_ledger_asset_proof_retrieval_request_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Asset Proof Retrieval Request Execution Time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "scalardl_stats_ledger_asset_proof_retrieval_request{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_ledger_asset_proof_retrieval_request{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_ledger_asset_proof_retrieval_request{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_ledger_asset_proof_retrieval_request{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_ledger_asset_proof_retrieval_request{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_ledger_asset_proof_retrieval_request{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Ledger Validation Request Per One Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(irate(scalardl_stats_ledger_ledger_validation_request{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardl_stats_ledger_ledger_validation_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardl_stats_ledger_ledger_validation_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Ledger Validation Request Execution Time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "scalardl_stats_ledger_ledger_validation_request{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_ledger_ledger_validation_request{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_ledger_ledger_validation_request{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_ledger_ledger_validation_request{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_ledger_ledger_validation_request{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardl_stats_ledger_ledger_validation_request{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  }
 ]
}