apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scalar-manager.fullname" . }}-api-application-properties
  namespace: {{ .Release.Namespace }}
data:
  scalar-manager-api-application.properties:
    {{- toYaml .Values.api.applicationProperties | nindent 4 }}
