apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scalar-manager.fullname" . }}-api-application-properties
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scalar-manager.labels" . | nindent 4 }}
data:
  scalar-manager-api-application.properties:
    {{- toYaml .Values.api.applicationProperties | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scalar-manager.fullname" . }}-web-env-file
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scalar-manager.labels" . | nindent 4 }}
data:
  scalar-manager-web-env-file:
    {{- toYaml .Values.web.env | nindent 4 }}
