apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scalar-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/app: {{ include "scalar-manager.fullname" . }}
    {{- include "scalar-manager.labels" . | nindent 4 }}
data:
  managed-clusters: "[]"
  paused-states: "[]"
  paused-states-updated-at: "0"
