apiVersion: v1
kind: Service
metadata:
  name: {{ include "scalar-manager.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scalar-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - protocol: TCP
      name: web
      port: {{ .Values.web.service.port }}
      targetPort: 3000
  selector:
    {{- include "scalar-manager.selectorLabels" . | nindent 4 }}
