apiVersion: v1
kind: Service
metadata:
  name: {{ include "scalar-manager.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scalar-manager.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.scalarManager.web.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.scalarManager.web.service.type }}
  ports:
  {{- range $key, $value := .Values.scalarManager.web.service.ports }}
    - name: {{ $key }}
{{ toYaml $value | indent 6 }}
  {{- end }}
  selector:
    {{- include "scalar-manager.selectorLabels" . | nindent 4 }}
