apiVersion: v2
name: scalardb
description: A Helm chart of Scalar DB

type: application
version: 2.0.0
appVersion: 3.1.0
deprecated: false
icon: https://scalar-labs.com/wp-content/themes/scalar/assets/img/logo_scalar.svg
keywords:
- scalardb
- scalardb-server
home: https://scalar-labs.com/
sources:
  - https://github.com/scalar-labs/scalardb/tree/master/server
maintainers:
  - name: Pham Ba Thong
    email: thong.pham@scalar-labs.com
