# Default values for schema-loading.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

schemaLoading:
  # -- The database to which the schema is loaded. `cassandra` and `cosmos` are supported.
  database: cassandra
  # -- The database contanct point such as a hostname of Cassandra or a URL of Cosmos DB account.
  contactPoints: cassandra
  # -- The database port number. (Ignored if the database is `cosmos`.)
  contactPort: 9042
  # -- The username of the database. (Ignored if the database is `cosmos`.)
  username: cassandra
  # -- The password of the database. For Cosmos DB, please specify a key here.
  password: cassandra
  # -- The replication factor value of the Cassandra schema. This is a Cassandra specific option.
  cassandraReplicationFactor: 1
  # schemaLoading.cassandraReplicationStrategy -- The replication strategy of the Cassandra schema. This is a Cassandra specific option.
  cassandraReplicationStrategy: SimpleStrategy
  # schemaLoading.cosmosBaseResourceUnit -- The resource unit value of the Cosmos DB schema. This is a Cosmos DB specific option.
  cosmosBaseResourceUnit: 400
  # -- The resource unit value of the DynamoDB schema. This is a DynamoDB specific option.
  dynamoBaseResourceUnit: 10

  image:
    # -- Docker image
    repository: ghcr.io/scalar-labs/scalardl-schema-loader
    # -- Docker tag
    version: 3.2.0
    # -- Specify a imagePullPolicy
    pullPolicy: IfNotPresent

  # -- Optionally specify an array of imagePullSecrets. Secrets must be manually created in the namespace.
  imagePullSecrets: [name: reg-docker-secrets]

  # -- Name of existing secret to use for storing database username and password
  existingSecret: null

  # schemaLoading.schemaType -- Type of schema to apply (ledger or auditor).
  schemaType: ledger
