apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "scalar-admin-k8s.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "deployments", "services"]
    verbs: ["get", "list"]
