{
 "title": "ScalarDB Cluster / Overview",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": {
     "query": "label_values(scalardb_cluster_stats_total_success, pod) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Success Requests per one second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_stats_total_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failure Requests per one second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_stats_total_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Distributed Transaction Admin Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Create table per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_stats_distributed_transaction_admin_create_table_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Create table execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_admin_create_table{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_admin_create_table{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_admin_create_table{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_admin_create_table{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_admin_create_table{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_admin_create_table{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Drop table per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_stats_distributed_transaction_admin_drop_table_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Drop table execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_admin_drop_table{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_admin_drop_table{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_admin_drop_table{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_admin_drop_table{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_admin_drop_table{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_admin_drop_table{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Truncate table per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_stats_distributed_transaction_admin_truncate_table_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Truncate table execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_admin_truncate_table{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_admin_truncate_table{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_admin_truncate_table{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_admin_truncate_table{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_admin_truncate_table{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_admin_truncate_table{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Get table metadata per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_stats_distributed_transaction_admin_get_table_metadata_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Get table metadata execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_admin_get_table_metadata{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_admin_get_table_metadata{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_admin_get_table_metadata{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_admin_get_table_metadata{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_admin_get_table_metadata{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_admin_get_table_metadata{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Distributed Transaction Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Transaction begin per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_stats_distributed_transaction_begin_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transaction begin execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_begin{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_begin{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_begin{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_begin{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_begin{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_begin{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction get per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_stats_distributed_transaction_get_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transaction get execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_get{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_get{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_get{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_get{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_get{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_get{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction scan per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_stats_distributed_transaction_scan_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transaction scan execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_scan{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_scan{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_scan{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_scan{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_scan{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_scan{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction put per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_stats_distributed_transaction_put_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transaction put execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_put{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_put{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_put{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_put{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_put{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_put{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction delete per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_stats_distributed_transaction_delete_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transaction delete execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_delete{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_delete{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_delete{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_delete{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_delete{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_delete{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction mutate per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_stats_distributed_transaction_mutate_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transaction mutate execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_mutate{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_mutate{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_mutate{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_mutate{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_mutate{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_mutate{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction commit per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_stats_distributed_transaction_commit_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transaction commit execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_commit{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_commit{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_commit{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_commit{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_commit{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_commit{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction rollback per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_stats_distributed_transaction_rollback_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transaction rollback execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "targets": [
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_rollback{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_rollback{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_rollback{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_rollback{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_rollback{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_distributed_transaction_rollback{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Two Phase Commit Transaction Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Transaction begin per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_begin_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_begin_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_begin_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Transaction begin execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "targets": [
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_begin{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_begin{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_begin{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_begin{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_begin{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_begin{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction join per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_join_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_join_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_join_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Transaction join execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "targets": [
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_join{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_join{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_join{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_join{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_join{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_join{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction get per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_get_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_get_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_get_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Transaction get execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "targets": [
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_get{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_get{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_get{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_get{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_get{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_get{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction scan per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_scan_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_scan_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_scan_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Transaction scan execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
   "targets": [
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_scan{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_scan{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_scan{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_scan{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_scan{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_scan{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction put per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_put_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_put_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_put_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Transaction put execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 139 },
   "targets": [
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_put{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_put{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_put{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_put{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_put{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_put{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction delete per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 147 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_delete_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_delete_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_delete_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Transaction delete execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 147 },
   "targets": [
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_delete{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_delete{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_delete{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_delete{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_delete{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_delete{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction mutate per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 155 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_mutate_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_mutate_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_mutate_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Transaction mutate execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 155 },
   "targets": [
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_mutate{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_mutate{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_mutate{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_mutate{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_mutate{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_mutate{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction prepare per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 163 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_prepare_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_prepare_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_prepare_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Transaction prepare execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 163 },
   "targets": [
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_prepare{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_prepare{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_prepare{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_prepare{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_prepare{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_prepare{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction validate per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 171 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_validate_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_validate_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_validate_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Transaction validate execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 171 },
   "targets": [
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_validate{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_validate{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_validate{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_validate{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_validate{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_validate{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction commit per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 179 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_commit_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_commit_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_commit_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Transaction commit execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 179 },
   "targets": [
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_commit{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_commit{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_commit{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_commit{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_commit{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_commit{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction rollback per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 187 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_rollback_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_rollback_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_cluster_stats_two_phase_commit_transaction_rollback_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Transaction rollback execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 187 },
   "targets": [
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_rollback{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_rollback{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_rollback{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_rollback{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_rollback{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_stats_two_phase_commit_transaction_rollback{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "GraphQL Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 195 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Success HTTP Requests per one second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_graphql_stats_http_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failure HTTP Requests per one second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_graphql_stats_http_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Success GraphQL Queries per one second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 203 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_graphql_stats_graphql_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failure GraphQL Queries per one second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 203 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_graphql_stats_graphql_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GraphQL execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 210 },
   "targets": [
    {
     "expr": "scalardb_cluster_graphql_stats_responses{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_graphql_stats_responses{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_graphql_stats_responses{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_graphql_stats_responses{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_graphql_stats_responses{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_graphql_stats_responses{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  { "title": "SQL Total Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 219 } },
  {
   "title": "Success SQL Requests per one second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 220 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_transaction_begin_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failure SQL Requests per one second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 220 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_total_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "SQL Distributed Transaction Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 227 }
  },
  {
   "title": "Transaction begin per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 228 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_transaction_begin_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_transaction_begin_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_transaction_begin_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Transaction begin execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 228 },
   "targets": [
    {
     "expr": "scalardb_cluster_sql_stats_sql_transaction_begin{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_transaction_begin{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_transaction_begin{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_transaction_begin{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_transaction_begin{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_transaction_begin{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction execute per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 236 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_transaction_execute_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_transaction_execute_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_transaction_execute_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Transaction execute execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 236 },
   "targets": [
    {
     "expr": "scalardb_cluster_sql_stats_sql_transaction_execute{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_transaction_execute{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_transaction_execute{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_transaction_execute{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_transaction_execute{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_transaction_execute{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction commit per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 244 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_transaction_commit_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_transaction_commit_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_transaction_commit_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Transaction commit execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 244 },
   "targets": [
    {
     "expr": "scalardb_cluster_sql_stats_sql_transaction_commit{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_transaction_commit{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_transaction_commit{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_transaction_commit{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_transaction_commit{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_transaction_commit{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction rollback per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 252 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_transaction_rollback_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_transaction_rollback_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_transaction_rollback_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Transaction rollback execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 252 },
   "targets": [
    {
     "expr": "scalardb_cluster_sql_stats_sql_transaction_rollback{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_transaction_rollback{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_transaction_rollback{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_transaction_rollback{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_transaction_rollback{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_transaction_rollback{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "SQL Two Phase Commit Transaction Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 260 }
  },
  {
   "title": "Transaction begin per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 261 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_begin_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_begin_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_begin_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Transaction begin execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 261 },
   "targets": [
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_begin{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_begin{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_begin{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_begin{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_begin{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_begin{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction join per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 269 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_join_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_join_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_join_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Transaction join execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 269 },
   "targets": [
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_join{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_join{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_join{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_join{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_join{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_join{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction execute per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 277 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_execute_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_execute_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_execute_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Transaction execute execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 277 },
   "targets": [
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_execute{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_execute{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_execute{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_execute{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_execute{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_execute{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction prepare per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 285 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_prepare_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_prepare_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_prepare_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Transaction prepare execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 285 },
   "targets": [
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_prepare{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_prepare{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_prepare{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_prepare{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_prepare{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_prepare{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction validate per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 293 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_validate_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_validate_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_validate_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Transaction validate execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 293 },
   "targets": [
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_validate{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_validate{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_validate{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_validate{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_validate{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_validate{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction commit per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 301 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_commit_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_commit_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_commit_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Transaction commit execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 301 },
   "targets": [
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_commit{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_commit{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_commit{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_commit{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_commit{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_commit{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Transaction rollback per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 309 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_rollback_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_rollback_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_rollback_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Transaction rollback execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 309 },
   "targets": [
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_rollback{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_rollback{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_rollback{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_rollback{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_rollback{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_sql_two_phase_commit_transaction_rollback{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  { "title": "SQL Metadata Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 317 } },
  {
   "title": "Get namespace metadata per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 318 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_metadata_get_namespace_metadata_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_metadata_get_namespace_metadata_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_metadata_get_namespace_metadata_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Get namespace metadata execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 318 },
   "targets": [
    {
     "expr": "scalardb_cluster_sql_stats_metadata_get_namespace_metadata{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_metadata_get_namespace_metadata{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_metadata_get_namespace_metadata{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_metadata_get_namespace_metadata{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_metadata_get_namespace_metadata{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_metadata_get_namespace_metadata{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Get table metadata per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 326 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_metadata_get_table_metadata_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_metadata_get_table_metadata_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_metadata_get_table_metadata_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "Get table metadata execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 326 },
   "targets": [
    {
     "expr": "scalardb_cluster_sql_stats_metadata_get_table_metadata{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_metadata_get_table_metadata{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_metadata_get_table_metadata{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_metadata_get_table_metadata{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_metadata_get_table_metadata{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_metadata_get_table_metadata{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "List table metadata in namespace per one second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 334 },
   "targets": [
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_metadata_list_table_metadata_in_namespace_count{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-all"
    },
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_metadata_list_table_metadata_in_namespace_success{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-success"
    },
    {
     "expr": "sum(irate(scalardb_cluster_sql_stats_metadata_list_table_metadata_in_namespace_failure{pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-failure"
    }
   ]
  },
  {
   "title": "List table metadata in namespace execution time (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 334 },
   "targets": [
    {
     "expr": "scalardb_cluster_sql_stats_metadata_list_table_metadata_in_namespace{quantile=\"0.5\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_metadata_list_table_metadata_in_namespace{quantile=\"0.75\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_metadata_list_table_metadata_in_namespace{quantile=\"0.95\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_metadata_list_table_metadata_in_namespace{quantile=\"0.98\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_metadata_list_table_metadata_in_namespace{quantile=\"0.99\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    },
    {
     "expr": "scalardb_cluster_sql_stats_metadata_list_table_metadata_in_namespace{quantile=\"0.999\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  }
 ]
}