apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scalardl-audit.fullname" . }}-auditor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scalardl-audit-auditor.labels" . | nindent 4 }}
spec:
  minReadySeconds: 0
  replicas: {{ .Values.auditor.replicaCount }}
  selector:
    matchLabels:
      {{- include "scalardl-audit-auditor.selectorLabels" . | nindent 6 }}
  {{- with .Values.auditor.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/auditor/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "scalardl-audit-auditor.selectorLabels" . | nindent 8 }}
        {{- if eq .Values.global.platform "azure" }}
        azure-extensions-usage-release-identifier: {{ .Release.Name }}
        {{- end }}
    spec:
      restartPolicy: Always
      {{- if .Values.auditor.serviceAccount.serviceAccountName }}
      serviceAccountName: {{ .Values.auditor.serviceAccount.serviceAccountName }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.auditor.serviceAccount.automountServiceAccountToken }}
      terminationGracePeriodSeconds: 60
    {{- with .Values.auditor.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      {{- if not .Values.auditor.extraVolumes }}
        - name: "{{ .Values.auditor.scalarAuditorConfiguration.secretName }}"
          secret:
            secretName: "{{ .Values.auditor.scalarAuditorConfiguration.secretName }}"
      {{- end }}
        - name: scalardl-auditor-properties-volume
          configMap:
            name: {{ include "scalardl-audit.fullname" . }}-auditor-properties
      {{- if and .Values.auditor.tls.enabled .Values.auditor.tls.certManager.enabled }}
        - name: scalardl-auditor-tls-volume
          secret:
            secretName: {{ include "scalardl-audit.fullname" . }}-tls-cert
      {{- end }}
      {{- if and (.Values.auditor.tls.enabled) (not .Values.auditor.tls.certManager.enabled) }}
        - name: scalardl-auditor-tls-volume
          projected:
            sources:
              - secret:
                  name: {{ .Values.auditor.tls.caRootCertSecret }}
              - secret:
                  name: {{ .Values.auditor.tls.certChainSecret }}
              - secret:
                  name: {{ .Values.auditor.tls.privateKeySecret }}
      {{- end }}
      {{- if .Values.auditor.tls.enabled }}
        - name: scalardl-auditor-tls-for-ledger-volume
          secret:
            {{- if .Values.auditor.tls.caRootCertForLedgerSecret }}
            secretName: {{ .Values.auditor.tls.caRootCertForLedgerSecret }}
            {{- else }}
            secretName: {{ include "scalardl-audit.fullname" . }}-tls-cert
            {{- end }}
      {{- end }}
      {{- with .Values.auditor.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.auditor.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-auditor
          securityContext:
            {{- toYaml .Values.auditor.securityContext | nindent 12 }}
          {{- if eq .Values.global.platform "azure" }}
          image: "{{ .Values.global.azure.images.scalardbCluster.registry }}/{{ .Values.global.azure.images.scalardbCluster.image }}:{{ .Values.global.azure.images.scalardbCluster.tag }}"
          {{- else }}
          image: "{{ .Values.auditor.image.repository }}:{{ .Values.auditor.image.version }}"
          {{- end }}
          imagePullPolicy: {{ .Values.auditor.image.pullPolicy }}
          volumeMounts:
          {{- if not .Values.auditor.extraVolumeMounts }}
            - name: "{{ .Values.auditor.scalarAuditorConfiguration.secretName }}"
              mountPath: "/keys"
              readOnly: true
          {{- end }}
            - name: scalardl-auditor-properties-volume
              mountPath: /scalar/auditor/auditor.properties
              subPath: auditor.properties
          {{- if .Values.auditor.tls.enabled }}
            - name: scalardl-auditor-tls-volume
              mountPath: /tls/scalardl-auditor/certs
            - name: scalardl-auditor-tls-for-ledger-volume
              mountPath: /tls/scalardl-ledger/certs
          {{- end }}
          {{- with .Values.auditor.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
          - containerPort: 40051
          - containerPort: 40052
          - containerPort: 40053
          - containerPort: 8080
          env:
          - name: HELM_SCALAR_DB_CONTACT_POINTS
            value: "{{ .Values.auditor.scalarAuditorConfiguration.dbContactPoints }}"
          - name: HELM_SCALAR_DB_CONTACT_PORT
            value: "{{ .Values.auditor.scalarAuditorConfiguration.dbContactPort }}"
          - name: HELM_SCALAR_DB_USERNAME
            valueFrom:
              secretKeyRef:
              {{- if .Values.auditor.existingSecret }}
                name: {{ .Values.auditor.existingSecret }}
              {{- else }}
                name: {{ include "scalardl-audit.fullname" . }}-auditor
              {{- end }}
                key: db-username
          - name: HELM_SCALAR_DB_PASSWORD
            valueFrom:
              secretKeyRef:
              {{- if .Values.auditor.existingSecret }}
                name: {{ .Values.auditor.existingSecret }}
              {{- else }}
                name: {{ include "scalardl-audit.fullname" . }}-auditor
              {{- end }}
                key: db-password
          - name: HELM_SCALAR_DB_STORAGE
            value: "{{ .Values.auditor.scalarAuditorConfiguration.dbStorage }}"
          - name: HELM_SCALAR_DL_AUDITOR_SERVER_PORT
            value: "{{ .Values.auditor.scalarAuditorConfiguration.auditorServerPort }}"
          - name: HELM_SCALAR_DL_AUDITOR_SERVER_PRIVILEGED_PORT
            value: "{{ .Values.auditor.scalarAuditorConfiguration.auditorServerPrivilegedPort }}"
          - name: HELM_SCALAR_DL_AUDITOR_SERVER_ADMIN_PORT
            value: "{{ .Values.auditor.scalarAuditorConfiguration.auditorServerAdminPort }}"
          - name: SCALAR_DL_AUDITOR_LOG_LEVEL
            value: "{{ .Values.auditor.scalarAuditorConfiguration.auditorLogLevel }}"
          - name: HELM_SCALAR_DL_AUDITOR_LEDGER_HOST
            value: "{{ .Values.auditor.scalarAuditorConfiguration.auditorLedgerHost }}"
          - name: HELM_SCALAR_DL_AUDITOR_CERT_HOLDER_ID
            value: "{{ .Values.auditor.scalarAuditorConfiguration.auditorCertHolderId }}"
          - name: HELM_SCALAR_DL_AUDITOR_CERT_VERSION
            value: "{{ .Values.auditor.scalarAuditorConfiguration.auditorCertVersion }}"
          - name: HELM_SCALAR_DL_AUDITOR_CERT_PATH
            value: "/keys/{{ .Values.auditor.scalarAuditorConfiguration.auditorCertSecretKey }}"
          - name: HELM_SCALAR_DL_AUDITOR_PRIVATE_KEY_PATH
            value: "/keys/{{ .Values.auditor.scalarAuditorConfiguration.auditorPrivateKeySecretKey }}"
          {{- if .Values.auditor.secretName }}
          envFrom:
          - secretRef:
              name: "{{ .Values.auditor.secretName }}"
          {{- end }}
          startupProbe:
            exec:
              command:
              - /usr/local/bin/grpc_health_probe
              - -addr=localhost:40051
              {{- if .Values.auditor.tls.enabled }}
              - -tls
              - -tls-ca-cert=/tls/scalardl-auditor/certs/ca.crt
              {{- if .Values.auditor.tls.overrideAuthority }}
              - -tls-server-name={{ .Values.auditor.tls.overrideAuthority }}
              {{- end }}
              {{- end }}
            failureThreshold: 60
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
              - /usr/local/bin/grpc_health_probe
              - -addr=localhost:40051
              {{- if .Values.auditor.tls.enabled }}
              - -tls
              - -tls-ca-cert=/tls/scalardl-auditor/certs/ca.crt
              {{- if .Values.auditor.tls.overrideAuthority }}
              - -tls-server-name={{ .Values.auditor.tls.overrideAuthority }}
              {{- end }}
              {{- end }}
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            {{- toYaml .Values.auditor.resources | nindent 12 }}
      {{- with .Values.auditor.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.auditor.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.auditor.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
