{{- if not .Values.auditor.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scalardl-audit.fullname" . }}-auditor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scalardl-audit-auditor.labels" . | nindent 4 }}
type: Opaque
data:
  db-username: {{ .Values.auditor.scalarAuditorConfiguration.dbUsername | b64enc | quote }}
  db-password: {{ .Values.auditor.scalarAuditorConfiguration.dbPassword | b64enc | quote }}
{{- end -}}
