apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scalardb-cluster.fullname" . }}-node-properties
  namespace: {{ .Release.Namespace }}
data:
  # Create a scalardb-cluster-node.properties file which is config file of ScalarDB Cluster.
  scalardb-cluster-node.properties:
    {{- toYaml .Values.scalardbCluster.scalardbClusterNodeProperties | nindent 4 }}
---
{{- if .Values.scalardbCluster.grafanaDashboard.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scalardb-cluster.fullname" . }}-grafana-dashboard
  labels:
    grafana_dashboard: "1"
    {{- include "scalardb-cluster.labels" . | nindent 4 }}
{{- if .Values.scalardbCluster.grafanaDashboard.namespace }}
  namespace: {{ .Values.scalardbCluster.grafanaDashboard.namespace }}
{{- end }}
data:
{{- range $path, $_ :=  .Files.Glob  "files/grafana/scalardb_cluster_*.json" }}
  {{ $path | base }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
{{- end }}
---
{{- if eq .Values.global.platform "google" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scalardb-cluster.fullname" . }}-ubbagent-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scalardb-cluster.labels" . | nindent 4 }}
data:
  ubbagent-config.yaml: |
    identities:
      - name: google-marketplace-auth
        gcp:
          encodedServiceAccountKey: ${AGENT_ENCODED_KEY}
    metrics:
      - name: scalardb_cluster_enterprise_premium
        type: int
        endpoints:
          - name: servicecontrol-premium
          - name: disk
        passthrough: {}
      - name: scalardb_cluster_enterprise_standard
        type: int
        endpoints:
          - name: servicecontrol-standard
          - name: disk
        passthrough: {}
    endpoints:
      - name: servicecontrol-premium
        servicecontrol:
          identity: google-marketplace-auth
          serviceName: scalardb-cluster-enterprise-premium.endpoints.scalarlabs-public.cloud.goog
          consumerId: ${AGENT_CONSUMER_ID}
      - name: servicecontrol-standard
        servicecontrol:
          identity: google-marketplace-auth
          serviceName: scalardb-cluster-enterprise-standard.endpoints.scalarlabs-public.cloud.goog
          consumerId: ${AGENT_CONSUMER_ID}
      - name: disk
        disk:
          reportDir: /tmp/ubbagent/reports
          expireSeconds: 10800
{{- end }}
