apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "scalardb-cluster.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "watch", "list"]
