{{- if not .Values.scalardbCluster.serviceAccount.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scalardb-cluster.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scalardb-cluster.labels" . | nindent 4 }}
{{- end }}