{{- if .Values.scalardbCluster.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scalardb-cluster.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scalardb-cluster.labels" . | nindent 4 }}
{{- end }}
{{- if .Values.scalardbCluster.rbac.serviceAccountAnnotations }}
  annotations:
{{ toYaml .Values.scalardbCluster.rbac.serviceAccountAnnotations | nindent 4 }}
{{- end }}
