{{- if not .Values.scalardb.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scalardb.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scalardb.labels" . | nindent 4 }}
type: Opaque
data:
  db-username: {{ .Values.scalardb.storageConfiguration.username | b64enc | quote }}
  db-password: {{ .Values.scalardb.storageConfiguration.password | b64enc | quote }}
{{- end -}}
