{{- if not .Values.scalardb.useCustomizedConfiguration.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scalardb.fullname" . }}-config-file
  namespace: {{ .Release.Namespace }}
data:
  # Create a database.properties file which is config file of Scalar DB server.
  database.properties: |-
    scalar.db.contact_points={{.Values.scalardb.storageConfiguration.contactPoints}}
    scalar.db.contact_port={{.Values.scalardb.storageConfiguration.contactPort}}
    scalar.db.username={{.Values.scalardb.storageConfiguration.username}}
    scalar.db.password={{.Values.scalardb.storageConfiguration.password}}
    scalar.db.storage={{.Values.scalardb.storageConfiguration.storage}}
    scalar.db.server.port=50051
{{- end }}
---
{{- if .Values.scalardb.grafanaDashboard.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scalardb.fullname" . }}-grafana-dashboard
  labels:
    grafana_dashboard: "1"
    {{- include "scalardb.labels" . | nindent 4 }}
{{- if .Values.scalardb.grafanaDashboard.namespace }}
  namespace: {{ .Values.scalardb.grafanaDashboard.namespace }}
{{- end }}
data:
{{- range $path, $_ :=  .Files.Glob  "files/grafana/scalardb_*.json" }}
  {{ $path | base }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
{{- end }}
