apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scalardb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scalardb.labels" . | nindent 4 }}
spec:
  minReadySeconds: 0
  replicas: {{ .Values.scalardb.replicaCount }}
  selector:
    matchLabels:
      {{- include "scalardb.selectorLabels" . | nindent 6 }}
  {{- with .Values.scalardb.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
    {{- if .Values.scalardb.podAnnotations }}
      annotations:
        {{- toYaml .Values.scalardb.podAnnotations | nindent 8 }}
    {{- end }}
      labels:
        {{- include "scalardb.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.scalardb.rbac.create }}
      serviceAccountName: {{ include "scalardb.fullname" . }}
      {{- end }}
      restartPolicy: Always
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 60
      {{- with .Values.scalardb.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.scalardb.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.scalardb.securityContext | nindent 12 }}
          image: "{{ .Values.scalardb.image.repository }}:{{ .Values.scalardb.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.scalardb.image.pullPolicy }}
          ports:
            - containerPort: 60051
            - containerPort: 8080
          {{- if not .Values.scalardb.useCustomizedConfiguration.enabled }}
          env:
          - name: SCALAR_DB_CONTACT_POINTS
            value: "{{ .Values.scalardb.storageConfiguration.contactPoints }}"
          - name: SCALAR_DB_CONTACT_PORT
            value: "{{ .Values.scalardb.storageConfiguration.contactPort }}"
          - name: SCALAR_DB_USERNAME
            valueFrom:
              secretKeyRef:
              {{- if .Values.scalardb.existingSecret }}
                name: {{ .Values.scalardb.existingSecret }}
              {{- else }}
                name: {{ include "scalardb.fullname" . }}-secret
              {{- end }}
                key: db-username
          - name: SCALAR_DB_PASSWORD
            valueFrom:
              secretKeyRef:
              {{- if .Values.scalardb.existingSecret }}
                name: {{ .Values.scalardb.existingSecret }}
              {{- else }}
                name: {{ include "scalardb.fullname" . }}-secret
              {{- end }}
                key: db-password
          - name: SCALAR_DB_STORAGE
            value: "{{ .Values.scalardb.storageConfiguration.storage }}"
          - name: SCALAR_DB_LOG_LEVEL
            value: "{{ .Values.scalardb.storageConfiguration.dbLogLevel }}"
          {{- end }}
          {{- if .Values.scalardb.useCustomizedConfiguration.secretName }}
          envFrom:
          - secretRef:
              name: "{{ .Values.scalardb.useCustomizedConfiguration.secretName }}"
          {{- end }}
          resources:
            {{- toYaml .Values.scalardb.resources | nindent 12 }}
          livenessProbe:
            exec:
              command:
              - /usr/local/bin/grpc_health_probe
              - -addr=:60051
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
      {{- if .Values.scalardb.useCustomizedConfiguration.enabled }}
          volumeMounts:
            - name: scalardb-customized-config-file-volume
              mountPath: /scalardb/server/database.properties.tmpl
              subPath: database.properties.tmpl
      volumes:
        - name: scalardb-customized-config-file-volume
          configMap:
            name: {{ .Values.scalardb.useCustomizedConfiguration.configMapName }}
      {{- end }}
      {{- with .Values.scalardb.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scalardb.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scalardb.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
