{{- if .Values.scalardb.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scalardb.fullname" . }}
  labels:
    {{- include "scalardb.labels" . | nindent 4 }}
{{- end }}
{{- if .Values.scalardb.rbac.serviceAccountAnnotations }}
  annotations:
{{ toYaml .Values.scalardb.rbac.serviceAccountAnnotations | nindent 4 }}
{{- end }}
