{{- if .Values.tls.downstream.certManager.enabled }}
# Generate a server certificate for the Envoy
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "envoy.fullname" . }}-envoy-tls-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "envoy.labels" . | nindent 4 }}
spec:
  secretName: {{ include "envoy.fullname" . }}-envoy-tls-cert
  secretTemplate:
    labels:
      {{- include "envoy.labels" . | nindent 6 }}
  duration: {{ .Values.tls.downstream.certManager.duration | quote }}
  renewBefore: {{ .Values.tls.downstream.certManager.renewBefore | quote }}
  privateKey:
    {{- toYaml .Values.tls.downstream.certManager.privateKey | nindent 4 }}
  usages:
    {{- range .Values.tls.downstream.certManager.usages }}
    - {{ . | quote }}
    {{- end }}
  dnsNames:
    {{- range .Values.tls.downstream.certManager.dnsNames }}
    - {{ . | quote }}
    {{- end }}
  issuerRef:
    {{- if .Values.tls.downstream.certManager.issuerRef }}
    {{- toYaml .Values.tls.downstream.certManager.issuerRef | nindent 4 }}
    {{- else }}
    # If you don't specify issuerRef, this chart uses self-signed CA generated by the ScalarDB Cluster or ScalarDL chart.
    name: {{ include "envoy.fullname" . }}-ca-issuer
    {{- end }}
{{- end }}
