{{- if .Values.schemaLoading.databaseProperties }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "schema-loading.fullname" . }}-database-properties
  namespace: {{ .Release.Namespace }}
data:
  # Create a database.properties file which is config file of Schema Loader.
  database.properties.tmpl:
    {{- toYaml .Values.schemaLoading.databaseProperties | nindent 4 }}
{{- end }}
