apiVersion: v2
name: scalardl-audit
description: ScalarDL is a tamper-evident and scalable distributed database. This chart adds an auditing capability to Ledger (scalardl chart).
type: application
version: 3.0.0-SNAPSHOT
appVersion: 4.0.0-SNAPSHOT
deprecated: false
icon: https://scalar-labs.com/wp-content/themes/scalar/assets/img/logo_scalar.svg
keywords:
- "database"
- "distributed ledger"
- "scalar"
- "scalardl"
home: https://scalar-labs.com/
sources:
  - https://github.com/scalar-labs/scalardl
dependencies:
- name: envoy
  version: ~3.0.0-SNAPSHOT
  repository: file://../envoy/
  condition: envoy.enabled
maintainers:
  - name: Takanori Yokoyama
    email: takanori.yokoyama@scalar-labs.com
  - name: Hiroyuki Yamada
    email: hiroyuki.yamada@scalar-labs.com
