# Default values for scalardl-audit.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# nameOverride -- String to partially override scalardl-audit.fullname template (will maintain the release name)
nameOverride: ""

# fullnameOverride -- String to fully override scalardl-audit.fullname template
fullnameOverride: ""

envoy:
  # envoy.replicaCount -- number of replicas to deploy
  replicaCount: 3

  envoyConfiguration:
    # envoy.envoyConfiguration.adminAccessLogPath -- admin log path
    adminAccessLogPath: /dev/stdout

  image:
    # envoy.image.repository -- Docker image
    repository: ghcr.io/scalar-labs/scalar-envoy
    # envoy.image.tag -- Docker tag
    version: 1.1.0
    # envoy.image.pullPolicy -- Specify a imagePullPolicy
    pullPolicy: IfNotPresent

  # envoy.imagePullSecrets -- Optionally specify an array of imagePullSecrets. Secrets must be manually created in the namespace.
  imagePullSecrets: []

  strategy:
    rollingUpdate:
      # envoy.strategy.rollingUpdate -- The number of pods that can be created above the desired amount of pods during an update
      maxSurge: 25%
      # envoy.strategy.rollingUpdate -- The number of pods that can be unavailable during the update process
      maxUnavailable: 25%
    # envoy.strategy.type -- New pods are added gradually, and old pods are terminated gradually, e.g: Recreate or RollingUpdate
    type: RollingUpdate

  # envoy.podSecurityContext -- PodSecurityContext holds pod-level security attributes and common container settings
  podSecurityContext:
    {}
    # fsGroup: 2000

  # envoy.securityContext -- Setting security context at the pod applies those settings to all containers in the pod
  securityContext:
    {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  service:
    # envoy.service.type -- service types in kubernetes
    type: ClusterIP
    # envoy.service.annotations -- Service annotations, e.g: prometheus, etc.
    annotations: {}
    ports:
      envoy:
        # envoy.service.ports.envoy.port -- envoy public port
        port: 40051
        # envoy.service.ports.envoy.targetPort -- envoy k8s internal name
        targetPort: 50051
        # envoy.service.ports.envoy.protocol -- envoy protocol
        protocol: TCP
      envoy-priv:
        # envoy.service.ports.envoy-priv.port -- nvoy public port
        port: 40052
        # envoy.service.ports.envoy-priv.targetPort -- envoy k8s internal name
        targetPort: 50052
        # envoy.service.ports.envoy-priv.protocol -- envoy protocol
        protocol: TCP

  serviceMonitor:
    # envoy.serviceMonitor.enabled -- enable metrics collect with prometheus
    enabled: false
    # envoy.serviceMonitor.interval -- custom interval to retrieve the metrics
    interval: "15s"
    # envoy.serviceMonitor.namespace -- which namespace prometheus is located. by default monitoring
    namespace: monitoring

  prometheusRule:
    # envoy.prometheusRule.enabled -- enable rules for prometheus
    enabled: false
    # envoy.prometheusRule.namespace -- which namespace prometheus is located. by default monitoring
    namespace: monitoring

  grafanaDashboard:
    # auditor.grafanaDashboard.enabled -- enable grafana dashboard
    enabled: false
    # auditor.grafanaDashboard.namespace -- which namespace grafana dashboard is located. by default monitoring
    namespace: monitoring

  # envoy.resources -- resources allowed to the pod
  resources:
    {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # envoy.nodeSelector -- nodeSelector is form of node selection constraint
  nodeSelector: {}

  # envoy.tolerations -- Tolerations are applied to pods, and allow (but do not require) the pods to schedule onto nodes with matching taints.
  tolerations: []

  # envoy.affinity -- the affinity/anti-affinity feature, greatly expands the types of constraints you can express
  affinity: {}

auditor:
  # auditor.replicaCount -- number of replicas to deploy
  replicaCount: 3

  scalarAuditorConfiguration:
    # auditor.scalarAuditorConfiguration.dbContactPoints -- The contact points of the database such as hostnames or URLs
    dbContactPoints: cassandra
    # auditor.scalarAuditorConfiguration.dbContactPort -- The port number of the contact points
    dbContactPort: 9042
    # auditor.scalarAuditorConfiguration.dbUsername -- The username of the database
    dbUsername: cassandra
    # auditor.scalarAuditorConfiguration.dbPassword -- The password of the database
    dbPassword: cassandra
    # auditor.scalarAuditorConfiguration.dbStorage -- The storage of the database: cassandra or cosmos
    dbStorage: cassandra
    # auditor.scalarAuditorConfiguration.auditorServerPort -- The port number of Auditor Server
    auditorServerPort: 50051
    # auditor.scalarAuditorConfiguration.auditorServerPrivilegedPort -- The port number of Auditor Privileged Server
    auditorServerPrivilegedPort: 50052
    # auditor.scalarAuditorConfiguration.auditorServerAdminPort -- The port number of Auditor Admin Server
    auditorServerAdminPort: 50053
    # auditor.scalarAuditorConfiguration.auditorLogLevel -- The log level of Scalar auditor
    auditorLogLevel: INFO
    # auditor.scalarAuditorConfiguration.auditorCertHolderId -- The holder ID of an Auditor certificate
    auditorCertHolderId: auditor
    # auditor.scalarAuditorConfiguration.auditorCertVersion -- The version of an Auditor certificate
    auditorCertVersion: 1

  image:
    # auditor.image.repository -- Docker image
    repository: ghcr.io/scalar-labs/scalar-auditor
    # auditor.image.version -- Docker tag
    version: 3.0.1
    # auditor.image.pullPolicy -- Specify a imagePullPolicy
    pullPolicy: IfNotPresent

  # auditor.imagePullSecrets -- Optionally specify an array of imagePullSecrets. Secrets must be manually created in the namespace.
  imagePullSecrets: [name: reg-docker-secrets]

  strategy:
    rollingUpdate:
      # auditor.strategy.rollingUpdate -- The number of pods that can be created above the desired amount of pods during an update
      maxSurge: 25%
      # auditor.strategy.rollingUpdate -- The number of pods that can be unavailable during the update process
      maxUnavailable: 25%
    # auditor.strategy.type -- New pods are added gradually, and old pods are terminated gradually, e.g: Recreate or RollingUpdate
    type: RollingUpdate

  # auditor.podSecurityContext -- PodSecurityContext holds pod-level security attributes and common container settings
  podSecurityContext:
    {}
    # fsGroup: 2000

  # auditor.securityContext -- Setting security context at the pod applies those settings to all containers in the pod
  securityContext:
    {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    # auditor.service.type -- service types in kubernetes
    type: ClusterIP
    annotations: {}
    ports:
      scalardl-auditor:
        # auditor.service.ports.scalardl.port -- scalardl target port
        port: 50051
        # auditor.service.ports.scalardl.targetPort -- scalardl k8s internal name
        targetPort: 50051
        # auditor.service.ports.scalardl.protocol -- scalardl protocol
        protocol: TCP
      scalardl-auditor-priv:
        # auditor.service.ports.scalardl-priv.port -- scalardl-priv target port
        port: 50052
        # auditor.service.ports.scalardl-priv.targetPort -- scalardl-priv k8s internal name
        targetPort: 50052
        # auditor.service.ports.scalardl-priv.protocol -- scalardl-priv protocol
        protocol: TCP
      scalardl-auditor-admin:
        # auditor.service.ports.scalardl-admin.port -- scalardl-admin target port
        port: 50053
        # auditor.service.ports.scalardl-admin.targetPort -- scalardl-admin k8s internal name
        targetPort: 50053
        # auditor.service.ports.scalardl-admin.protocol -- scalardl-admin protocol
        protocol: TCP

  prometheusRule:
    # auditor.prometheusRule.enabled -- enable rules for prometheus
    enabled: false
    # auditor.prometheusRule.namespace -- which namespace prometheus is located. by default monitoring
    namespace: monitoring

  grafanaDashboard:
    # auditor.grafanaDashboard.enabled -- enable grafana dashboard
    enabled: false
    # auditor.grafanaDashboard.namespace -- which namespace grafana dashboard is located. by default monitoring
    namespace: monitoring

  # auditor.resources -- resources allowed to the pod
  resources:
    {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # auditor.nodeSelector -- nodeSelector is form of node selection constraint
  nodeSelector: {}

  # auditor.tolerations -- Tolerations are applied to pods, and allow (but do not require) the pods to schedule onto nodes with matching taints.
  tolerations: []

  # auditor.affinity -- the affinity/anti-affinity feature, greatly expands the types of constraints you can express
  affinity: {}

  # auditor.existingSecret -- Name of existing secret to use for storing database username and password
  existingSecret: null
